"""
Modul na drzanie informacii o itemoch
meno itemu, meno ikonky, rarita
"""
from cases.load_items import *

icon_list = [
    {"name": "benjos_masterpiece", "rarity": 2, "collection": "class", "icon": BENJOS_MASTERPIECE},
    {"name": "berta", "rarity": 1, "collection": "class", "icon": BERTA},
    {"name": "birdhouse", "rarity": 2, "collection": "class", "icon": BIRDHOUSE},
    {"name": "black_marker", "rarity": 4, "collection": "class", "icon": BLACK_MARKER},
    {"name": "blue_marker", "rarity": 4, "collection": "class", "icon": BLUE_MARKER},
    {"name": "bonsai", "rarity": 2, "collection": "class", "icon": BONSAI},
    {"name": "chewed_pen", "rarity": 4, "collection": "class", "icon": CHEWED_PEN},
    {"name": "class_angel", "rarity": 4, "collection": "class", "icon": CLASS_ANGEL},
    {"name": "classmade_dart", "rarity": 3, "collection": "class", "icon": CLASSMADE_DART},
    {"name": "crucifix", "rarity": 2, "collection": "class", "icon": CRUCIFIX},
    {"name": "cursed_object", "rarity": 3, "collection": "class", "icon": CURSED_OBJECT},
    {"name": "eraser", "rarity": 4, "collection": "class", "icon": ERASER},
    {"name": "face_mask", "rarity": 4, "collection": "class", "icon": FACE_MASK},
    {"name": "founders_picture", "rarity": 1, "collection": "class", "icon": FOUNDERS_PICTURE},
    {"name": "gerta", "rarity": 1, "collection": "class", "icon": GERTA},
    {"name": "green_marker", "rarity": 4, "collection": "class", "icon": GREEN_MARKER},
    {"name": "grzes_angel", "rarity": 3, "collection": "class", "icon": GRZES_ANGEL},
    {"name": "helpful_ladybug", "rarity": 3, "collection": "class", "icon": HELPFUL_LADYBUG},
    {"name": "holy_bible", "rarity": 1, "collection": "class", "icon": HOLY_BIBLE},
    {"name": "laser_remote", "rarity": 2, "collection": "class", "icon": LASER_REMOTE},
    {"name": "monstromon", "rarity": 3, "collection": "class", "icon": MONSTROMON},
    {"name": "petroleum_mirror", "rarity": 2, "collection": "class", "icon": PETROLEUM_MIRROR},
    {"name": "red_marker", "rarity": 4, "collection": "class", "icon": RED_MARKER},
    {"name": "saints_hat", "rarity": 3, "collection": "class", "icon": SAINTS_HAT},
    {"name": "shamlik", "rarity": 3, "collection": "class", "icon": SHAMLIK},
    {"name": "soap", "rarity": 4, "collection": "class", "icon": SOAP},
    {"name": "toilet_paper", "rarity": 4, "collection": "class", "icon": TOILET_PAPER},
    {"name": "wanted_individual", "rarity": 3, "collection": "class", "icon": WANTED_INDIVIDUAL},

    {"name": "blue_botaks", "rarity": 3, "collection": "trip", "icon": BLUE_BOTAKS},
    {"name": "canned_gainz", "rarity": 3, "collection": "trip", "icon": CANNED_GAINZ},
    {"name": "chewed_gum", "rarity": 4, "collection": "trip", "icon": CHEWED_GUM},
    {"name": "earplugs", "rarity": 4, "collection": "trip", "icon": EARPLUGS},
    {"name": "fine_tea", "rarity": 4, "collection": "trip", "icon": FINE_TEA},
    {"name": "free_rose", "rarity": 2, "collection": "trip", "icon": FREE_ROSE},
    {"name": "hand_handicap", "rarity": 3, "collection": "trip", "icon": HAND_HANDICAP},
    {"name": "influencers_speciality", "rarity": 4, "collection": "trip", "icon": INFLUENCERS_SPECIALITY},
    {"name": "lemur_mask", "rarity": 1, "collection": "trip", "icon": LEMUR_MASK},
    {"name": "local_trdlo", "rarity": 4, "collection": "trip", "icon": LOCAL_TRDLO},
    {"name": "marslakocskak_imunactiv", "rarity": 2, "collection": "trip", "icon": MARSLAKOCSKAK_IMUNACTIV},
    {"name": "marslakocskak_inulinnal", "rarity": 2, "collection": "trip", "icon": MARSLAKOCSKAK_INULINNAL},
    {"name": "metro_ticket", "rarity": 3, "collection": "trip", "icon": METRO_TICKET},
    {"name": "monkey_mask", "rarity": 1, "collection": "trip", "icon": MONKEY_MASK},
    {"name": "obese_hotdog", "rarity": 4, "collection": "trip", "icon": OBESE_HOTDOG},
    {"name": "old_tv", "rarity": 4, "collection": "trip", "icon": OLD_TV},
    {"name": "passport", "rarity": 2, "collection": "trip", "icon": PASSPORT},
    {"name": "piss_ticket", "rarity": 3, "collection": "trip", "icon": PISS_TICKET},
    {"name": "playing_cards", "rarity": 4, "collection": "trip", "icon": PLAYING_CARDS},
    {"name": "rasputin_forints", "rarity": 3, "collection": "trip", "icon": RASPUTIN_FORINTS},
    {"name": "shark_mask", "rarity": 1, "collection": "trip", "icon": SHARK_MASK},
    {"name": "subway_cup", "rarity": 4, "collection": "trip", "icon": SUBWAY_CUP},
    {"name": "the_flasha", "rarity": 4, "collection": "trip", "icon": THE_FLASHA},
    {"name": "tick_on_my_leg", "rarity": 2, "collection": "trip", "icon": TICK_ON_MY_LEG},
    {"name": "tiger_mask", "rarity": 1, "collection": "trip", "icon": TIGER_MASK},
    {"name": "toilet_map", "rarity": 2, "collection": "trip", "icon": TOILET_MAP},
    {"name": "warholpiece", "rarity": 3, "collection": "trip", "icon": WARHOLPIECE},
    {"name": "writers_keyboard", "rarity": 3, "collection": "trip", "icon": WRITERS_KEYBOARD},
]
