"""
Module na loadovanie itemov pre case appku
"""

import os
import pygame


from settings import ICON_SIZE

pygame.init()

path = "assets/items/"
CASE_LOADING = pygame.image.load(os.path.join(path, "loading.png"))
CASE_LOADING = pygame.transform.scale(CASE_LOADING, (400, 190))
COUNTER = pygame.image.load(os.path.join(path, "counter.png"))
COUNTER = pygame.transform.scale(COUNTER, (40, 40))
CLASS_COLLECTION_OPEN = pygame.image.load(os.path.join(path, "class_collection_open.png"))
CLASS_COLLECTION_OPEN = pygame.transform.scale(CLASS_COLLECTION_OPEN, (500, 900))
TRIP_COLLECTION_OPEN = pygame.image.load(os.path.join(path, "trip_collection_open.png"))
TRIP_COLLECTION_OPEN = pygame.transform.scale(TRIP_COLLECTION_OPEN, (500, 900))
OPENING = pygame.image.load(os.path.join(path, "loading.png"))
OPENING = pygame.transform.scale(OPENING, (500, 900))

bgsize = 120
LEG_BG = pygame.image.load(os.path.join(path, "leg_bg.png"))
LEG_BG = pygame.transform.scale(LEG_BG, (bgsize, bgsize))
SR_BG = pygame.image.load(os.path.join(path, "sr_bg.png"))
SR_BG = pygame.transform.scale(SR_BG, (bgsize, bgsize))
R_BG = pygame.image.load(os.path.join(path, "r_bg.png"))
R_BG = pygame.transform.scale(R_BG, (bgsize, bgsize))
C_BG = pygame.image.load(os.path.join(path, "c_bg.png"))
C_BG = pygame.transform.scale(C_BG, (bgsize, bgsize))

path = "assets/items/otvorene_casy/"
CLASS_OPEN_C = pygame.image.load(os.path.join(path, "class_open_c.png"))
CLASS_OPEN_C = pygame.transform.scale(CLASS_OPEN_C, (500, 900))
CLASS_OPEN_L = pygame.image.load(os.path.join(path, "class_open_l.png"))
CLASS_OPEN_L = pygame.transform.scale(CLASS_OPEN_L, (500, 900))
CLASS_OPEN_R = pygame.image.load(os.path.join(path, "class_open_r.png"))
CLASS_OPEN_R = pygame.transform.scale(CLASS_OPEN_R, (500, 900))
CLASS_OPEN_SR = pygame.image.load(os.path.join(path, "class_open_sr.png"))
CLASS_OPEN_SR = pygame.transform.scale(CLASS_OPEN_SR, (500, 900))

TRIP_OPEN_C = pygame.image.load(os.path.join(path, "trip_open_c.png"))
TRIP_OPEN_C = pygame.transform.scale(TRIP_OPEN_C, (500, 900))
TRIP_OPEN_L = pygame.image.load(os.path.join(path, "trip_open_l.png"))
TRIP_OPEN_L = pygame.transform.scale(TRIP_OPEN_L, (500, 900))
TRIP_OPEN_R = pygame.image.load(os.path.join(path, "trip_open_r.png"))
TRIP_OPEN_R = pygame.transform.scale(TRIP_OPEN_R, (500, 900))
TRIP_OPEN_SR = pygame.image.load(os.path.join(path, "trip_open_sr.png"))
TRIP_OPEN_SR = pygame.transform.scale(TRIP_OPEN_SR, (500, 900))


# Class Collection
path = "assets/items/class_collection/"
BENJOS_MASTERPIECE = pygame.image.load(os.path.join(path, "benjos_masterpiece-2.png"))
BENJOS_MASTERPIECE = pygame.transform.scale(BENJOS_MASTERPIECE, (ICON_SIZE, ICON_SIZE))
BERTA = pygame.image.load(os.path.join(path, "berta-1.png"))
BERTA = pygame.transform.scale(BERTA, (ICON_SIZE, ICON_SIZE))
BIRDHOUSE = pygame.image.load(os.path.join(path, "birdhouse-2.png"))
BIRDHOUSE = pygame.transform.scale(BIRDHOUSE, (ICON_SIZE, ICON_SIZE))
BLACK_MARKER = pygame.image.load(os.path.join(path, "black_marker-4.png"))
BLACK_MARKER = pygame.transform.scale(BLACK_MARKER, (ICON_SIZE, ICON_SIZE))
BLUE_MARKER = pygame.image.load(os.path.join(path, "blue_marker-4.png"))
BLUE_MARKER = pygame.transform.scale(BLUE_MARKER, (ICON_SIZE, ICON_SIZE))
BONSAI = pygame.image.load(os.path.join(path, "bonsai-2.png"))
BONSAI = pygame.transform.scale(BONSAI, (ICON_SIZE, ICON_SIZE))
CHEWED_PEN = pygame.image.load(os.path.join(path, "chewed_pen_4.png"))
CHEWED_PEN = pygame.transform.scale(CHEWED_PEN, (ICON_SIZE, ICON_SIZE))
CLASS_ANGEL = pygame.image.load(os.path.join(path, "class_angel-4.png"))
CLASS_ANGEL = pygame.transform.scale(CLASS_ANGEL, (ICON_SIZE, ICON_SIZE))
CLASSMADE_DART = pygame.image.load(os.path.join(path, "classmade_dart-3.png"))
CLASSMADE_DART = pygame.transform.scale(CLASSMADE_DART, (ICON_SIZE, ICON_SIZE))
CRUCIFIX = pygame.image.load(os.path.join(path, "crucifix-2.png"))
CRUCIFIX = pygame.transform.scale(CRUCIFIX, (ICON_SIZE, ICON_SIZE))
CURSED_OBJECT = pygame.image.load(os.path.join(path, "cursed_object-3.png"))
CURSED_OBJECT = pygame.transform.scale(CURSED_OBJECT, (ICON_SIZE, ICON_SIZE))
ERASER = pygame.image.load(os.path.join(path, "eraser-4.png"))
ERASER = pygame.transform.scale(ERASER, (ICON_SIZE, ICON_SIZE))
FACE_MASK = pygame.image.load(os.path.join(path, "face_mask-4.png"))
FACE_MASK = pygame.transform.scale(FACE_MASK, (ICON_SIZE, ICON_SIZE))
FOUNDERS_PICTURE = pygame.image.load(os.path.join(path, "founders_picture-1.png"))
FOUNDERS_PICTURE = pygame.transform.scale(FOUNDERS_PICTURE, (ICON_SIZE, ICON_SIZE))
GERTA = pygame.image.load(os.path.join(path, "gerta-1.png"))
GERTA = pygame.transform.scale(GERTA, (ICON_SIZE, ICON_SIZE))
GREEN_MARKER = pygame.image.load(os.path.join(path, "green_marker-4.png"))
GREEN_MARKER = pygame.transform.scale(GREEN_MARKER, (ICON_SIZE, ICON_SIZE))
GRZES_ANGEL = pygame.image.load(os.path.join(path, "grzes_angel-3.png"))
GRZES_ANGEL = pygame.transform.scale(GRZES_ANGEL, (ICON_SIZE, ICON_SIZE))
HELPFUL_LADYBUG = pygame.image.load(os.path.join(path, "helpful_ladybug-3.png"))
HELPFUL_LADYBUG = pygame.transform.scale(HELPFUL_LADYBUG, (ICON_SIZE, ICON_SIZE))
HOLY_BIBLE = pygame.image.load(os.path.join(path, "holy_bible-1.png"))
HOLY_BIBLE = pygame.transform.scale(HOLY_BIBLE, (ICON_SIZE, ICON_SIZE))
LASER_REMOTE = pygame.image.load(os.path.join(path, "laser_remote-2.png"))
LASER_REMOTE = pygame.transform.scale(LASER_REMOTE, (ICON_SIZE, ICON_SIZE))
MONSTROMON = pygame.image.load(os.path.join(path, "monstromon-3.png"))
MONSTROMON = pygame.transform.scale(MONSTROMON, (ICON_SIZE, ICON_SIZE))
PETROLEUM_MIRROR = pygame.image.load(os.path.join(path, "petroleum_mirror-2.png"))
PETROLEUM_MIRROR = pygame.transform.scale(PETROLEUM_MIRROR, (ICON_SIZE, ICON_SIZE))
RED_MARKER = pygame.image.load(os.path.join(path, "red_marker-4.png"))
RED_MARKER = pygame.transform.scale(RED_MARKER, (ICON_SIZE, ICON_SIZE))
SAINTS_HAT = pygame.image.load(os.path.join(path, "saints_hat-3.png"))
SAINTS_HAT = pygame.transform.scale(SAINTS_HAT, (ICON_SIZE, ICON_SIZE))
SHAMLIK = pygame.image.load(os.path.join(path, "shamlik-3.png"))
SHAMLIK = pygame.transform.scale(SHAMLIK, (ICON_SIZE, ICON_SIZE))
SOAP = pygame.image.load(os.path.join(path, "soap-4.png"))
SOAP = pygame.transform.scale(SOAP, (ICON_SIZE, ICON_SIZE))
TOILET_PAPER = pygame.image.load(os.path.join(path, "toiled_paper-4.png"))
TOILET_PAPER = pygame.transform.scale(TOILET_PAPER, (ICON_SIZE, ICON_SIZE))
WANTED_INDIVIDUAL = pygame.image.load(os.path.join(path, "wanted_individual-3.png"))
WANTED_INDIVIDUAL = pygame.transform.scale(WANTED_INDIVIDUAL, (ICON_SIZE, ICON_SIZE))

# Trip Collection
path = "assets/items/trip_collection/"
BLUE_BOTAKS = pygame.image.load(os.path.join(path, "blue_botaks-3.png"))
BLUE_BOTAKS = pygame.transform.scale(BLUE_BOTAKS, (ICON_SIZE, ICON_SIZE))
CANNED_GAINZ = pygame.image.load(os.path.join(path, "canned_gainz-3.png"))
CANNED_GAINZ = pygame.transform.scale(CANNED_GAINZ, (ICON_SIZE, ICON_SIZE))
CHEWED_GUM = pygame.image.load(os.path.join(path, "chewed_gum-4.png"))
CHEWED_GUM = pygame.transform.scale(CHEWED_GUM, (ICON_SIZE, ICON_SIZE))
EARPLUGS = pygame.image.load(os.path.join(path, "earplugs-4.png"))
EARPLUGS = pygame.transform.scale(EARPLUGS, (ICON_SIZE, ICON_SIZE))
FINE_TEA = pygame.image.load(os.path.join(path, "fine_tea-4.png"))
FINE_TEA = pygame.transform.scale(FINE_TEA, (ICON_SIZE, ICON_SIZE))
FREE_ROSE = pygame.image.load(os.path.join(path, "free_rose-2.png"))
FREE_ROSE = pygame.transform.scale(FREE_ROSE, (ICON_SIZE, ICON_SIZE))
HAND_HANDICAP = pygame.image.load(os.path.join(path, "hand_handicap-3.png"))
HAND_HANDICAP = pygame.transform.scale(HAND_HANDICAP, (ICON_SIZE, ICON_SIZE))
INFLUENCERS_SPECIALITY = pygame.image.load(os.path.join(path, "influencers_speciality-4.png"))
INFLUENCERS_SPECIALITY = pygame.transform.scale(INFLUENCERS_SPECIALITY, (ICON_SIZE, ICON_SIZE))
LEMUR_MASK = pygame.image.load(os.path.join(path, "lemur_mask-1.png"))
LEMUR_MASK = pygame.transform.scale(LEMUR_MASK, (ICON_SIZE, ICON_SIZE))
LOCAL_TRDLO = pygame.image.load(os.path.join(path, "local_trdlo-4.png"))
LOCAL_TRDLO = pygame.transform.scale(LOCAL_TRDLO, (ICON_SIZE, ICON_SIZE))
MARSLAKOCSKAK_IMUNACTIV = pygame.image.load(os.path.join(path, "marslakocskak_imunactiv-2.png"))
MARSLAKOCSKAK_IMUNACTIV = pygame.transform.scale(MARSLAKOCSKAK_IMUNACTIV, (ICON_SIZE, ICON_SIZE))
MARSLAKOCSKAK_INULINNAL = pygame.image.load(os.path.join(path, "marslakocskak_inulinnal-2.png"))
MARSLAKOCSKAK_INULINNAL = pygame.transform.scale(MARSLAKOCSKAK_INULINNAL, (ICON_SIZE, ICON_SIZE))
METRO_TICKET = pygame.image.load(os.path.join(path, "metro_ticket-3.png"))
METRO_TICKET = pygame.transform.scale(METRO_TICKET, (ICON_SIZE, ICON_SIZE))
MONKEY_MASK = pygame.image.load(os.path.join(path, "monkey_mask-1.png"))
MONKEY_MASK = pygame.transform.scale(MONKEY_MASK, (ICON_SIZE, ICON_SIZE))
OBESE_HOTDOG = pygame.image.load(os.path.join(path, "obese_hotdog-4.png"))
OBESE_HOTDOG = pygame.transform.scale(OBESE_HOTDOG, (ICON_SIZE, ICON_SIZE))
OLD_TV = pygame.image.load(os.path.join(path, "old_tv-4.png"))
OLD_TV = pygame.transform.scale(OLD_TV, (ICON_SIZE, ICON_SIZE))
PASSPORT = pygame.image.load(os.path.join(path, "passport-2.png"))
PASSPORT = pygame.transform.scale(PASSPORT, (ICON_SIZE, ICON_SIZE))
PISS_TICKET = pygame.image.load(os.path.join(path, "piss_ticket-3.png"))
PISS_TICKET = pygame.transform.scale(PISS_TICKET, (ICON_SIZE, ICON_SIZE))
PLAYING_CARDS = pygame.image.load(os.path.join(path, "playing_cards-4.png"))
PLAYING_CARDS = pygame.transform.scale(PLAYING_CARDS, (ICON_SIZE, ICON_SIZE))
RASPUTIN_FORINTS = pygame.image.load(os.path.join(path, "rasputin_forints-3.png"))
RASPUTIN_FORINTS = pygame.transform.scale(RASPUTIN_FORINTS, (ICON_SIZE, ICON_SIZE))
SHARK_MASK = pygame.image.load(os.path.join(path, "shark_mask-1.png"))
SHARK_MASK = pygame.transform.scale(SHARK_MASK, (ICON_SIZE, ICON_SIZE))
SUBWAY_CUP = pygame.image.load(os.path.join(path, "subway_cup-4.png"))
SUBWAY_CUP = pygame.transform.scale(SUBWAY_CUP, (ICON_SIZE, ICON_SIZE))
THE_FLASHA = pygame.image.load(os.path.join(path, "the_flasha-4.png"))
THE_FLASHA = pygame.transform.scale(THE_FLASHA, (ICON_SIZE, ICON_SIZE))
TICK_ON_MY_LEG = pygame.image.load(os.path.join(path, "tick_on_my_leg-2.png"))
TICK_ON_MY_LEG = pygame.transform.scale(TICK_ON_MY_LEG, (ICON_SIZE, ICON_SIZE))
TIGER_MASK = pygame.image.load(os.path.join(path, "tiger_mask-1.png"))
TIGER_MASK = pygame.transform.scale(TIGER_MASK, (ICON_SIZE, ICON_SIZE))
TOILET_MAP = pygame.image.load(os.path.join(path, "toilet_map-2.png"))
TOILET_MAP = pygame.transform.scale(TOILET_MAP, (ICON_SIZE, ICON_SIZE))
WARHOLPIECE = pygame.image.load(os.path.join(path, "warholpiece-3.png"))
WARHOLPIECE = pygame.transform.scale(WARHOLPIECE, (ICON_SIZE, ICON_SIZE))
WRITERS_KEYBOARD = pygame.image.load(os.path.join(path, "writers_keyboard-3.png"))
WRITERS_KEYBOARD = pygame.transform.scale(WRITERS_KEYBOARD, (ICON_SIZE, ICON_SIZE))
